default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  timeout: 100
  default_transaction_mode: immediate

development:
  primary:
    <<: *default
    database: storage/db/development.sqlite3
  queue:
    <<: *default
    database: storage/db/development_queue.sqlite3
    migrations_paths: db/queue_migrate

test:
  primary:
    <<: *default
    database: storage/db/test.sqlite3
  queue:
    <<: *default
    database: storage/db/test_queue.sqlite3
    migrations_paths: db/queue_migrate

production:
  primary:
    <<: *default
    database: storage/db/production.sqlite3
  queue:
    <<: *default
    database: storage/db/production_queue.sqlite3
    migrations_paths: db/queue_migrate
